import { storage } from "../storage";

// Simple PDF generation function that creates basic HTML and converts to PDF
export async function generateWeeklyReport(userId: string, weekStart: string): Promise<Buffer> {
  try {
    // Get user data
    const user = await storage.getUser(userId);
    if (!user) throw new Error("User not found");

    // Get habits and logs for the week
    const habits = await storage.getUserHabits(userId);
    const weekEnd = new Date(weekStart);
    weekEnd.setDate(weekEnd.getDate() + 6);
    
    // Get all habit logs for the week
    const allLogs = await Promise.all(
      habits.map(async (habit) => {
        const logs = await storage.getHabitLogs(
          habit.id,
          weekStart,
          weekEnd.toISOString().split('T')[0]
        );
        return { habit, logs };
      })
    );

    // Get AI insights
    const insights = await storage.getWeeklyInsight(userId, weekStart);

    // Calculate statistics
    const totalPossibleHabits = habits.length * 7;
    const completedHabits = allLogs.reduce((sum, { logs }) => 
      sum + logs.filter(log => log.completed).length, 0
    );
    const completionRate = totalPossibleHabits > 0 ? Math.round((completedHabits / totalPossibleHabits) * 100) : 0;

    // Generate HTML report
    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Weekly Habit Report</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
          .header { text-align: center; margin-bottom: 40px; }
          .stats { display: flex; justify-content: space-around; margin-bottom: 30px; }
          .stat { text-align: center; }
          .stat-value { font-size: 24px; font-weight: bold; color: #10b981; }
          .habit-list { margin-bottom: 30px; }
          .habit { margin-bottom: 20px; padding: 15px; border: 1px solid #e5e7eb; border-radius: 8px; }
          .habit-name { font-weight: bold; font-size: 18px; margin-bottom: 5px; }
          .habit-stats { color: #6b7280; }
          .insights { background: #f9fafb; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
          .insights h3 { margin-top: 0; color: #1f2937; }
          .page-break { page-break-before: always; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Weekly Habit Report</h1>
          <h2>${user.firstName} ${user.lastName}</h2>
          <p>Week of ${new Date(weekStart).toLocaleDateString()} - ${weekEnd.toLocaleDateString()}</p>
        </div>

        <div class="stats">
          <div class="stat">
            <div class="stat-value">${completionRate}%</div>
            <div>Completion Rate</div>
          </div>
          <div class="stat">
            <div class="stat-value">${user.currentStreak}</div>
            <div>Current Streak</div>
          </div>
          <div class="stat">
            <div class="stat-value">${completedHabits}</div>
            <div>Habits Completed</div>
          </div>
          <div class="stat">
            <div class="stat-value">${user.totalPoints}</div>
            <div>Total Points</div>
          </div>
        </div>

        <div class="habit-list">
          <h3>Habit Performance</h3>
          ${allLogs.map(({ habit, logs }) => {
            const completed = logs.filter(log => log.completed).length;
            const rate = Math.round((completed / 7) * 100);
            return `
              <div class="habit">
                <div class="habit-name">${habit.name}</div>
                <div class="habit-stats">${completed}/7 days completed (${rate}%)</div>
                <div class="habit-stats">Category: ${habit.category}</div>
              </div>
            `;
          }).join('')}
        </div>

        ${insights ? `
          <div class="insights">
            <h3>AI-Generated Insights</h3>
            <p><strong>Analysis:</strong> ${insights.insights}</p>
            <p><strong>Recommendations:</strong> ${insights.recommendations}</p>
            <p><strong>Motivation:</strong> ${insights.motivationalTip}</p>
          </div>
        ` : ''}

        <div style="text-align: center; margin-top: 40px; color: #6b7280;">
          <p>Generated by HabitFlow • ${new Date().toLocaleDateString()}</p>
        </div>
      </body>
      </html>
    `;

    // In a real implementation, you would use a library like puppeteer or wkhtmltopdf
    // For this example, we'll return the HTML as a buffer
    return Buffer.from(html, 'utf-8');
    
  } catch (error) {
    console.error("Failed to generate PDF report:", error);
    throw new Error("Failed to generate weekly report");
  }
}
